version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app/iterview
permissions:
  - object: /home/ec2-user/app/iterview
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 60
      runas: root
